### ISSUE TITLE
Animated profile pictures

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-meme#3]
We were discussing with Milan about allowing to set a gif image as profile picture. I'm sure this was working before, and the apps should handle it well. 

But now if you upload an animated profile picture (to public folder on memes), when you access it from the public url it's downloaded as a static image. Some process is converting it from animated to static when uploaded.

**Comment by tomastiminskas** [comment]
@Evanfeenstra if you can take a look to see if I'm right and if it's easy to fix it would be great, but not top priority

**Comment by Evanfeenstra** [comment]
Like the file extension changes to not be `.gif` @tomastiminskas ? What exactly do you mean it becomes a static image

**Comment by tomastiminskas** [comment]
@Evanfeenstra it could be on the app side that it's converting it to a static image before uploading it. Will check deeply into it and let you know.

**Comment by tomastiminskas** [comment]
Closing this issue because the problem it's on the app side
